import fs from 'node:fs';
import path from 'node:path';

import {
  GraphJson,
  GraphNode,
  readGraphJson,
  validateGraph,
} from './validateGraph';

export interface ReferenceBuilding {
  code: string;
  name: string;
}

export interface ReferenceRoomFeature {
  featureId: number;
  name: string;
  description?: string;
}

export interface ReferencePathFeature {
  featureId: number;
  name: string;
  description?: string;
}

export interface ReferenceData {
  buildings?: ReferenceBuilding[];
  roomFeatures?: ReferenceRoomFeature[];
  pathFeatures?: ReferencePathFeature[];
}

export function readReferenceData(referenceDataPath?: string): ReferenceData {
  if (!referenceDataPath || !fs.existsSync(referenceDataPath)) {
    return {};
  }

  return JSON.parse(
    fs.readFileSync(referenceDataPath, 'utf8'),
  ) as ReferenceData;
}

function sqlString(value: unknown): string {
  if (value === null || value === undefined) {
    return 'NULL';
  }

  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

function nodeFloor(node: GraphNode): number {
  return Number(node.position?.floorNum ?? 0);
}

function nodeX(node: GraphNode): number {
  return Number(node.position?.x ?? 0);
}

function nodeY(node: GraphNode): number {
  return Number(node.position?.y ?? 0);
}

function roomCode(node: GraphNode): string {
  return (node.roomNumber ?? '').trim();
}

export function generateSeedSql(
  graph: GraphJson,
  referenceData: ReferenceData = {},
): string {
  const nodes = graph.nodes;

  if (!Array.isArray(nodes)) {
    throw new Error('graph.json must contain a top-level nodes array');
  }

  const nodeIds = new Set(nodes.map(node => node.id));
  const roomNodes = nodes.filter(node => node.kind === 'room');
  const pathNodes = nodes.filter(node => node.kind === 'path');

  const labeledRooms = roomNodes.map(roomCode).filter(code => code.length > 0);
  const inferredBuildingCode =
    labeledRooms.length > 0 ? labeledRooms[0][0].toUpperCase() : 'T';

  const referenceBuildings = referenceData.buildings ?? [];
  const matchingBuilding = referenceBuildings.find(
    building => building.code === inferredBuildingCode,
  );

  const buildingCode = matchingBuilding?.code ?? inferredBuildingCode;
  const buildingName = matchingBuilding?.name ?? `${buildingCode} Building`;

  const buildingsByCode = new Map<string, ReferenceBuilding>();

  for (const building of referenceBuildings) {
    buildingsByCode.set(building.code, building);
  }

  if (!buildingsByCode.has(buildingCode)) {
    buildingsByCode.set(buildingCode, {
      code: buildingCode,
      name: buildingName,
    });
  }

  const roomFeatureIds = [
    ...new Set(
      roomNodes
        .flatMap(node => node.features ?? [])
        .map(feature => Number(feature)),
    ),
  ].sort((a, b) => a - b);

  const pathFeatureIds = [
    ...new Set(
      pathNodes
        .flatMap(node => node.features ?? [])
        .map(feature => Number(feature)),
    ),
  ].sort((a, b) => a - b);

  const roomsByCode = new Map<string, GraphNode[]>();

  for (const node of roomNodes) {
    const code = roomCode(node);

    if (!code) {
      continue;
    }

    const current = roomsByCode.get(code) ?? [];
    current.push(node);
    roomsByCode.set(code, current);
  }

  const lines: string[] = [];

  lines.push('-- Auto-generated seed data for Campus Park 2 Path');
  lines.push(`-- Source graphId: ${graph.graphId ?? 'unknown'}`);
  lines.push(`-- Source savedAt: ${graph.savedAt ?? 'unknown'}`);
  lines.push('-- Generated by generateSeedSql.ts');
  lines.push('-- Run validateGraph.ts before generating this file.');
  lines.push(
    '-- Run this SQL AFTER selecting your database and running the schema.',
  );
  lines.push('');

  lines.push('SET FOREIGN_KEY_CHECKS = 0;');
  for (const table of [
    'edges',
    'room_feature_map',
    'path_feature_map',
    'room_nodes',
    'path_nodes',
    'graph_nodes',
    'rooms',
    'room_features',
    'path_features',
    'buildings',
  ]) {
    lines.push(`DELETE FROM ${table};`);
  }
  lines.push('SET FOREIGN_KEY_CHECKS = 1;');
  lines.push('');

  lines.push('-- Buildings');
  const buildingValues = [...buildingsByCode.values()]
    .sort((a, b) => a.code.localeCompare(b.code))
    .map(
      building => `(${sqlString(building.code)}, ${sqlString(building.name)})`,
    );

  lines.push('INSERT INTO buildings (code, name) VALUES');
  lines.push(`${buildingValues.join(',\n')};`);
  lines.push('');

  if (roomFeatureIds.length > 0) {
    lines.push('-- Room feature reference data');

    const referenceFeaturesById = new Map<number, ReferenceRoomFeature>();

    for (const feature of referenceData.roomFeatures ?? []) {
      referenceFeaturesById.set(Number(feature.featureId), feature);
    }

    const featureValues = roomFeatureIds.map(featureId => {
      const referenceFeature = referenceFeaturesById.get(featureId);

      const name = referenceFeature?.name ?? `graph_feature_${featureId}`;
      const description =
        referenceFeature?.description ??
        `Imported numeric feature id ${featureId} from graph.json`;

      return `(${featureId}, ${sqlString(name)}, ${sqlString(description)})`;
    });

    lines.push(
      'INSERT INTO room_features (feature_id, name, description) VALUES',
    );
    lines.push(`${featureValues.join(',\n')};`);
    lines.push('');
  }

  if (pathFeatureIds.length > 0) {
    lines.push('-- Path feature reference data');

    const referencePathFeaturesById = new Map<number, ReferencePathFeature>();

    for (const feature of referenceData.pathFeatures ?? []) {
      referencePathFeaturesById.set(Number(feature.featureId), feature);
    }

    const pathFeatureValues = pathFeatureIds.map(featureId => {
      const referenceFeature = referencePathFeaturesById.get(featureId);

      const name = referenceFeature?.name ?? `graph_feature_${featureId}`;
      const description =
        referenceFeature?.description ??
        `Imported numeric feature id ${featureId} from graph.json`;

      return `(${featureId}, ${sqlString(name)}, ${sqlString(description)})`;
    });

    lines.push(
      'INSERT INTO path_features (feature_id, name, description) VALUES',
    );
    lines.push(`${pathFeatureValues.join(',\n')};`);
    lines.push('');
  }

  lines.push(
    '-- Base graph nodes. Explicit graph_node_id preserves graph.json node ids for pathfinding.',
  );
  const graphNodeValues = nodes
    .slice()
    .sort((a, b) => a.id - b.id)
    .map(node =>
      [
        node.id,
        nodeX(node),
        nodeY(node),
        `(SELECT building_id FROM buildings WHERE code = ${sqlString(buildingCode)})`,
        nodeFloor(node),
        1,
      ].join(', '),
    )
    .map(value => `(${value})`);

  lines.push(
    'INSERT INTO graph_nodes (graph_node_id, x, y, building_id, floor, is_active) VALUES',
  );
  lines.push(`${graphNodeValues.join(',\n')};`);
  lines.push('');

  if (pathNodes.length > 0) {
    lines.push('-- Path nodes');
    const sortedPathNodes = pathNodes.slice().sort((a, b) => a.id - b.id);
    const pathNodeValues = sortedPathNodes.map(node => `(${node.id})`);

    lines.push('INSERT INTO path_nodes (graph_node_id) VALUES');
    lines.push(`${pathNodeValues.join(',\n')};`);
    lines.push('');

    const pathFeatureMapValues: string[] = [];

    for (const node of sortedPathNodes) {
      const featureIds = [
        ...new Set((node.features ?? []).map(feature => Number(feature))),
      ].sort((a, b) => a - b);

      for (const featureId of featureIds) {
        pathFeatureMapValues.push(`(${node.id}, ${featureId})`);
      }
    }

    if (pathFeatureMapValues.length > 0) {
      lines.push('-- Path features');
      lines.push(
        'INSERT INTO path_feature_map (graph_node_id, feature_id) VALUES',
      );
      lines.push(`${pathFeatureMapValues.join(',\n')};`);
      lines.push('');
    }
  }

  if (roomsByCode.size > 0) {
    lines.push('-- Rooms: one row per real roomNumber');
    const roomValues = [...roomsByCode.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([code, roomGraphNodes]) => {
        const first = roomGraphNodes.slice().sort((a, b) => a.id - b.id)[0];
        return `((SELECT building_id FROM buildings WHERE code = ${sqlString(buildingCode)}), ${sqlString(
          code,
        )}, ${sqlString(code)}, ${nodeFloor(first)}, 1)`;
      });

    lines.push(
      'INSERT INTO rooms (building_id, room_code, display_name, floor, is_active) VALUES',
    );
    lines.push(`${roomValues.join(',\n')};`);
    lines.push('');

    lines.push(
      '-- Room nodes: multiple graph nodes may point to the same room_id',
    );
    const roomNodeValues: string[] = [];

    for (const [code, roomGraphNodes] of [...roomsByCode.entries()].sort(
      ([a], [b]) => a.localeCompare(b),
    )) {
      for (const node of roomGraphNodes.slice().sort((a, b) => a.id - b.id)) {
        roomNodeValues.push(
          `(${node.id}, (SELECT room_id FROM rooms WHERE building_id = ` +
            `(SELECT building_id FROM buildings WHERE code = ${sqlString(buildingCode)}) ` +
            `AND room_code = ${sqlString(code)}))`,
        );
      }
    }

    lines.push('INSERT INTO room_nodes (graph_node_id, room_id) VALUES');
    lines.push(`${roomNodeValues.join(',\n')};`);
    lines.push('');

    const roomFeatureMapValues: string[] = [];

    for (const [code, roomGraphNodes] of [...roomsByCode.entries()].sort(
      ([a], [b]) => a.localeCompare(b),
    )) {
      const featureIds = [
        ...new Set(
          roomGraphNodes
            .flatMap(node => node.features ?? [])
            .map(feature => Number(feature)),
        ),
      ].sort((a, b) => a - b);

      for (const featureId of featureIds) {
        roomFeatureMapValues.push(
          '((SELECT room_id FROM rooms WHERE building_id = ' +
            `(SELECT building_id FROM buildings WHERE code = ${sqlString(buildingCode)}) ` +
            `AND room_code = ${sqlString(code)}), ${featureId})`,
        );
      }
    }

    if (roomFeatureMapValues.length > 0) {
      lines.push('-- Room features');
      lines.push('INSERT INTO room_feature_map (room_id, feature_id) VALUES');
      lines.push(`${roomFeatureMapValues.join(',\n')};`);
      lines.push('');
    }
  }

  lines.push('-- Edges: each JSON neighbor entry becomes one directed edge');
  const edgeValues: string[] = [];

  for (const node of nodes.slice().sort((a, b) => a.id - b.id)) {
    for (const neighbor of node.neighbors ?? []) {
      if (!nodeIds.has(neighbor.to)) {
        throw new Error(
          `Node ${node.id} points to missing node ${neighbor.to}. Run validateGraph.ts.`,
        );
      }

      edgeValues.push(
        `(${node.id}, ${neighbor.to}, ${Number(neighbor.distance)}, 1)`,
      );
    }
  }

  if (edgeValues.length > 0) {
    lines.push(
      'INSERT INTO edges (from_node_id, to_node_id, distance, is_active) VALUES',
    );
    lines.push(`${edgeValues.join(',\n')};`);
  }
  lines.push('');

  lines.push('-- Keep future AUTO_INCREMENT values above imported ids');
  if (nodeIds.size > 0) {
    lines.push(
      `ALTER TABLE graph_nodes AUTO_INCREMENT = ${Math.max(...nodeIds) + 1};`,
    );
  }
  if (roomFeatureIds.length > 0) {
    lines.push(
      `ALTER TABLE room_features AUTO_INCREMENT = ${Math.max(...roomFeatureIds) + 1};`,
    );
  }
  if (pathFeatureIds.length > 0) {
    lines.push(
      `ALTER TABLE path_features AUTO_INCREMENT = ${Math.max(...pathFeatureIds) + 1};`,
    );
  }
  lines.push('ALTER TABLE rooms AUTO_INCREMENT = 1;');
  lines.push('ALTER TABLE edges AUTO_INCREMENT = 1;');
  lines.push('');

  lines.push('-- Basic sanity checks');
  lines.push(
    "SELECT 'buildings' AS table_name, COUNT(*) AS row_count FROM buildings",
  );
  for (const table of [
    'rooms',
    'room_features',
    'room_feature_map',
    'graph_nodes',
    'path_nodes',
    'path_features',
    'path_feature_map',
    'room_nodes',
    'edges',
  ]) {
    lines.push(`UNION ALL SELECT '${table}', COUNT(*) FROM ${table}`);
  }
  lines.push(';');

  return lines.join('\n');
}

function parseArgs(argv: string[]): {
  graphPath?: string;
  outputPath?: string;
  referenceDataPath?: string;
  skipValidation: boolean;
} {
  const args = [...argv];

  let graphPath: string | undefined;
  let outputPath = 'database/seeds/seed_graph.sql';
  let outputPathWasSet = false;
  let referenceDataPath: string | undefined =
    'database/seeds/referenceData.json';
  let skipValidation = false;

  while (args.length > 0) {
    const arg = args.shift();

    if (arg === '--skip-validation') {
      skipValidation = true;
      continue;
    }

    if (arg === '--reference-data') {
      referenceDataPath = args.shift();
      continue;
    }

    if (!graphPath) {
      graphPath = arg;
      continue;
    }

    if (!outputPathWasSet && arg) {
      outputPath = arg;
      outputPathWasSet = true;
    }
  }

  return {graphPath, outputPath, referenceDataPath, skipValidation};
}

export function runGenerateSeedSqlCli(argv = process.argv.slice(2)): number {
  const {graphPath, outputPath, referenceDataPath, skipValidation} =
    parseArgs(argv);

  if (!graphPath || !outputPath) {
    console.error(
      'Usage: tsx database/scripts/generateSeedSql.ts <graph.json> [output.sql] [--skip-validation] [--reference-data <referenceData.json>]',
    );
    return 1;
  }

  const graph = readGraphJson(graphPath);

  if (!skipValidation) {
    const validation = validateGraph(graph);

    if (!validation.isValid) {
      console.error(
        'Validation failed. Fix graph.json before generating seed SQL.',
      );
      for (const error of validation.errors) {
        console.error(`- ${error}`);
      }
      return 1;
    }
  }

  const referenceData = readReferenceData(referenceDataPath);
  const sql = generateSeedSql(graph, referenceData);
  fs.mkdirSync(path.dirname(outputPath), {recursive: true});
  fs.writeFileSync(outputPath, `${sql}\n`, 'utf8');
  console.log(`Wrote ${outputPath}`);

  return 0;
}

if (process.argv[1]?.endsWith('generateSeedSql.ts')) {
  process.exitCode = runGenerateSeedSqlCli();
}
