export const FEATURE_LABELS: Record<number, string> = {
  1: "Men's Bathroom",
  2: "Men's Bathroom (Changing Table)",
  3: "Women's Bathroom",
  4: "Women's Bathroom (Changing Table)",
  5: 'Family Bathroom',
  6: 'All-Gender Bathroom',
  7: 'Elevator',
  8: 'Classroom',
  9: 'Vending Machine',
  10: 'Office',
  11: 'Parking Lot',
  12: 'Parking Garage',
  13: 'Café',
  14: 'Cafeteria',
  15: 'Library',
  16: 'Printers',
  17: 'Computer Lab',
  18: 'Prayer Room',
  19: 'Lactation Room',
  20: 'Shower',
  21: 'Gym',
  22: 'Lockers',
  23: 'Locker Room',
  24: 'Conference Room',
  25: 'Study Room',
  26: 'Study Room with Whiteboard',
  27: 'Smoke Shack',
  28: 'Parking Meter',
  29: 'Bus Stop',
  30: 'Emergency Phone',
  31: 'EV Charging Station',
  32: 'Other',
};
