name: Lint and Build

on:
  push:
  pull_request:

jobs:
  lint-build:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run compile
